  #letsPollRDSDatabase:
  #  Type: AWS::RDS::DBInstance
  #  Properties:
  #    DBInstanceClass: db.t2.micro
      #DBInstanceIdentifier: String
    #DBName: letsPoll
    #DBSubnetGroupName:
    #  Ref: letsPollPrivateSubnet1
    #Engine: postgres
    #EngineVersion: 9.4
    #MasterUsername: letsPollMasterDB
    #MasterUserPassword: Test12345A
    #MultiAZ: false
    #Port: 5432
    #PubliclyAccessible: false
    #SourceRegion: ap-south-1
    #VPCSecurityGroups:
    #  Ref: databaseSecurityGroup
  Resources:
    letsPollDBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds:
        - Ref: letsPollPrivateSubnet1
        - Ref: letsPollPrivateSubnet2
    letsPollDatabase:
      Type: "AWS::RDS::DBInstance"
      Properties:
        DBName: ${env.LP_DATABASE_USERNAME}
        AllocatedStorage: 5
        DBInstanceClass: "db.t2.micro"
        Engine: "postgres"
        EngineVersion: "9.5.4"
        MasterUsername: ${env.LP_DATABASE_USERNAME}
        MasterUserPassword: ${env.LP_DATABASE_USERNAME}
        VPCSecurityGroups:
          - "Fn::GetAtt": databaseSecurityGroup.GroupId
        DBSubnetGroupName:
          Ref: letsPollDBSubnetGroup
        Tags:
          -
            Key: "Name"
            Value: "forum_example"
      DeletionPolicy: "Snapshot"
