service:
  name: letspoll

#custom: ${file(./resources.yaml)}

frameworkVersion: ">=1.0.0 <2.0.0"


provider:
  name: aws
  runtime: java8
  stage: ${opt:stage,'beta'} # Set the default stage used. Default is dev
  region: ${opt:region,'ap-south-1'} # Overwrite the default region used. Default is us-east-1
  profile: ${opt:profile,'lets-poll-default'}
# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
resources:
  - ${file(./resources/vpc.yml)}
#  - ${file(./resources/rds.yml)}
  - ${file(./resources/cognito.yml)}




#Outputs:
#    letsPollVPCID:
#      Description: The VPC id for LetsPoll VPC
#      Value:
#        Ref: letsPollVPC
#      Export:
#        Name: ${self:service}:letsPollVPCId # see Fn::ImportValue to use in other services and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html for documentation on use.

#    letsPollIGWID:
#      Description: The VPC id for LetsPoll VPC
#      Value:
#        Ref: letsPollIGW
#      Export:
#        Name: ${self:service}:letsPollIGWId # see Fn::ImportValue to use in other services and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html for documentation on use.
