service:
  name: letspoll


frameworkVersion: ">=1.0.0 <2.0.0"


provider:
  name: aws
  runtime: java8
  stage: beta # Set the default stage used. Default is dev
  region: ap-south-1 # Overwrite the default region used. Default is us-east-1

# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
resources:
  Resources:
    letsPollVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 172.31.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        InstanceTenancy: default
        Tags:
             - Key: Name
               Value: Lets Poll VPC

    letsPollIGW:
        Type: AWS::EC2::InternetGateway

    letsPollVPCGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          VpcId:
            Ref: letsPollVPC
          InternetGatewayId:
            Ref: letsPollIGW

    letsPollPublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId:
            Ref: letsPollVPC
          AvailabilityZone: ap-south-1a
          CidrBlock: 172.31.0.0/20
          MapPublicIpOnLaunch: true
          Tags:
              - Key: Name
                Value: Lets Poll VPC Public Subnet 1

    letsPollPrivateSubnet1:
         Type: AWS::EC2::Subnet
         Properties:
           VpcId:
              Ref: letsPollVPC
           CidrBlock: 172.31.16.0/20
           AvailabilityZone: ap-south-1a
           MapPublicIpOnLaunch: false
           Tags:
               - Key: Name
                 Value: Lets Poll VPC Private Subnet 1

    letsPollPrivateSubnet2:
         Type: AWS::EC2::Subnet
         Properties:
           VpcId:
              Ref: letsPollVPC
           CidrBlock: 172.31.32.0/20
           AvailabilityZone: ap-south-1b
           MapPublicIpOnLaunch: false
           Tags:
               - Key: Name
                 Value: Lets Poll VPC Private Subnet 2

    letsPollVPCNatGateway1EIP:
        Type: AWS::EC2::EIP
        DependsOn: letsPollVPCGatewayAttachment
        Properties:
            Domain: vpc
    letsPollVPCNatGateway1:
        Type: AWS::EC2::NatGateway
        DependsOn: letsPollVPCNatGateway1EIP
        Properties:
            AllocationId:  { Fn::GetAtt: [ "letsPollVPCNatGateway1EIP", "AllocationId" ] }
            SubnetId:
              Ref: letsPollPublicSubnet
            Tags:
                - Key: Name
                  Value: Lets Poll VPC NAT Gateway 1
    letsPollVPCPublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId:
              Ref: letsPollVPC
            Tags:
                - Key: Name
                  Value: Lets Poll Public Subnet Route Table
    letsPollVPCDefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: letsPollVPCGatewayAttachment
        Properties:
          RouteTableId:
            Ref: letsPollVPCPublicRouteTable
          DestinationCidrBlock: 0.0.0.0/0
          NatGatewayId:
            Ref: letsPollVPCNatGateway1

    letsPollPublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          RouteTableId:
            Ref: letsPollVPCPublicRouteTable
          SubnetId:
            Ref: letsPollPublicSubnet

    letsPollPrivateRouteTable1:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId:
            Ref: letsPollVPC

    letsPollPrivateRouteTable2:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId:
           Ref: letsPollVPC


    letsPollDefaultPrivateRoute1:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: letsPollPrivateRouteTable1
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: letsPollVPCNatGateway1

    letsPollDefaultPrivateRoute2:
       Type: AWS::EC2::Route
       Properties:
         RouteTableId:
           Ref: letsPollPrivateRouteTable2
         DestinationCidrBlock: 0.0.0.0/0
         NatGatewayId:
           Ref: letsPollVPCNatGateway1

    letsPollPrivateSubnet1RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: letsPollPrivateRouteTable1
        SubnetId:
          Ref: letsPollPrivateSubnet1

    letsPollPrivateSubnet2RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: letsPollPrivateRouteTable2
        SubnetId:
           Ref: letsPollPrivateSubnet2




  Outputs:
    letsPollVPCID:
      Description: The VPC id for LetsPoll VPC
      Value:
        Ref: letsPollVPC
      Export:
        Name: ${self:service}:letsPollVPCId # see Fn::ImportValue to use in other services and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html for documentation on use.

    letsPollIGWID:
      Description: The VPC id for LetsPoll VPC
      Value:
        Ref: letsPollIGW
      Export:
        Name: ${self:service}:letsPollIGWId # see Fn::ImportValue to use in other services and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html for documentation on use.
